In [2]:
# for vs code
!pip install numpy

In [1]:
import numpy as np
print(np.__version__)

1.24.3


In [5]:
l=[1,2,3,4,5,6,7,8,9,10]
# converting list to numpy array
np_array= np.array(l)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# numpy array is made for computational operations rather than saving values
print(np_array+5)
print(np_array-5)
print(np_array*5)
print(np_array/5)

[ 6  7  8  9 10 11 12 13 14 15]
[-4 -3 -2 -1  0  1  2  3  4  5]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [7]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# shape of array
l=[1,2,3,4,5,6,7,8,9,10]
np_array= np.array(l)
print(np_array.shape)

(10,)


In [9]:
# numpy ma symmetric data ma kaam hunxa= no of columns same huna parxa
l=[[1,2,3],
   [4,5,6],
   [7,8,9]]
np_array= np.array(l)
print(np_array.shape)
# rows and column 

(3, 3)


In [10]:
print(np_array.dtype)
# int data type 32 bit taken

int32


In [12]:
l=[[[1],[2],[3]],
   [[4],[5],[6]],
   [[7],[8],[9]]]
np_array= np.array(l)
print(np_array.shape)
print(np_array.dtype)

(3, 3, 1)
int32


In [ ]:
# np array ma numerical values matra use hunxa

In [13]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
# sabai matirx values 0 ra 1 vayeko banauxa

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
l=[[1,2,3],
   [4,5,6]]
np_array= np.array(l)
np_array.reshape(3,2)
# 2*3 matrix lai 3*2 ma change gareko

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
# 6-> 2*3
# 6-> 3*2
# 6-> 1*6
# 6-> 6*1
print(np_array.reshape(3,2))
print(np_array.reshape(2,3))
print(np_array.reshape(1,6))
print(np_array.reshape(6,1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
np_array.flatten()

array([1, 2, 3, 4, 5, 6])

In [16]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([3,4,5,6,7,8,9,3,4])
a+b

array([ 4,  6,  8, 10, 12, 14, 16, 11, 13])

In [17]:
np.hstack((a,b))
# horizontal append

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4])

In [18]:
np.vstack((a,b))
# vertical append

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 4, 5, 6, 7, 8, 9, 3, 4]])

In [19]:
# random integers between 0,10 of shape 2,2
print(np.random.randint(0,10,size=[2,2]))

[[5 6]
 [8 1]]


In [20]:
print(np.random.randint(0,256,size=[8,8]))

[[115 190  26  70   2  86 201 171]
 [ 88 202 161 108 153  90  90  86]
 [ 76   4  63 105 232  46  28 219]
 [225 117  77   2 115 143  33  79]
 [133  52 144  76  24 159   4  25]
 [ 33 247 233 227 120 167 130  94]
 [225  53 218 184 176  29  56 206]
 [ 60 143 216  91   5 145  51 165]]


In [21]:
print(np.random.choice(['a','e','i','o','u'],size=10))
# a e i o u milayera random array banaune

['a' 'o' 'u' 'i' 'e' 'o' 'i' 'a' 'o' 'u']


In [22]:
print(np.random.choice(['a','e','i','o','u'],size=10, p=[0.3, 0.1, 0.1, 0.4, 0.1]))
# probability anusar characters print hunxa

['u' 'a' 'o' 'o' 'a' 'o' 'a' 'o' 'e' 'a']


In [2]:
# Statistical function
a=np.array([1,2,3,4,5,6,7,8,9,10])
print("min value=",np.min(a))
print("max value=",np.max(a))
print("sum value=",np.sum(a))
print("mean value=",np.mean(a))
print("median value=",np.median(a))
print("std value=",np.std(a))

min value= 1
max value= 10
sum value= 55
mean value= 5.5
median value= 5.5
std value= 2.8722813232690143


In [3]:
# arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,0.1)
# 0.1 ko gap ma print hunxa

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [5]:
# argmax
a=np.array([34,56,78,65,83,111])
np.argmax(a)
# largest value ko index return garxa

5

In [8]:
# scipy= numpy ley garna nasakne complex operations garxa
# linalg= linear algebra
import scipy.linalg as slin
import numpy as np
np_array=np.random.randint(0, 256, size=[8,8])
print(np_array)
slin.det(np_array)

[[154 236 128 203 160 209 158  53]
 [ 53  80 232 192  61 138  18  75]
 [229 183 125 187  20  31   5 228]
 [237 229  24 103 217 158   9  67]
 [ 54 119 163  38 154 205 236 254]
 [158  76 157 203  10 255  90 105]
 [228 196 105 162 153 158  42 231]
 [ 12 107 153 233 255   9  10  15]]


-6.701110087077018e+17

In [9]:
# trace=diagonal element ko sum
np_array=np.random.randint(0, 10, size=[3,3])
print(np_array)
np.trace(np_array)

[[4 7 1]
 [2 8 2]
 [0 3 7]]


19

In [10]:
np_array=np.random.randint(0, 10, size=[8,8])
slin.inv(np_array)

array([[-0.10667808,  0.16871902,  0.03478689,  0.08636764, -0.07630373,
        -0.26133072,  0.16816767,  0.0714122 ],
       [-0.03730416, -0.11838915, -0.02247967,  0.01595648,  0.22553417,
        -0.07718762, -0.12100463,  0.19501164],
       [-0.06993475,  0.12383462, -0.07103315,  0.06628635, -0.12933264,
        -0.01258634,  0.04348448,  0.07428871],
       [ 0.12890017, -0.05406269,  0.03201979, -0.14873422,  0.00599165,
         0.11339425,  0.10912471, -0.15977591],
       [ 0.6660596 , -0.60684091,  0.20572166, -0.52059388,  0.34340815,
         0.41918638, -0.29410346, -0.28759061],
       [-0.19955254,  0.16252578, -0.06752861,  0.24200065, -0.22795581,
        -0.04010228,  0.12075308,  0.04641612],
       [ 0.01863399,  0.03779866, -0.04128596,  0.07253386,  0.03795889,
        -0.0042592 , -0.07645536, -0.0266062 ],
       [-0.03440353,  0.14542352,  0.08963268, -0.05948404, -0.15514972,
         0.15072081,  0.02835158, -0.17256039]])

In [11]:
np_array=np.random.randint(0, 10, size=[2,2])
slin.inv(np_array)

array([[ 1.  , -1.75],
       [-1.  ,  2.  ]])

In [13]:
np_array=np.random.randint(0, 10, size=[3,3])
print(np_array)
np.transpose(np_array)

[[7 8 6]
 [0 9 9]
 [1 1 8]]


array([[7, 0, 1],
       [8, 9, 1],
       [6, 9, 8]])

In [14]:
a=np.matrix([[1,2,3],
            [3,4,2],
            [1,0,2]])
b=np.matrix([[3],
            [2],
            [1]])
a*b

matrix([[10],
        [19],
        [ 5]])

In [15]:
# eigen value problem
# to find the intersection points between linear lines
# find value of x y z in any 3 equations
# x1+y1+z1=a
# x2+y2+z2=b
# x3+y3+z3=c
mat=np.array([[1,2,3],[4,5,6],[4,5,6]])
np.linalg.eig(mat)

(array([ 1.27082039e+01, -7.08203932e-01, -2.65381787e-17]),
 array([[ 0.28907816,  0.90041255,  0.40824829],
        [ 0.67691721, -0.30761765, -0.81649658],
        [ 0.67691721, -0.30761765,  0.40824829]]))

In [19]:
import numpy as np
a=np.array([[1,1,1],
           [1,5,4],
           [3,2,2]])
b=np.array([2,5,6])
np.linalg.solve(a,b)

array([ 2.,  3., -3.])